#ifndef RENDERER_SHADERTESTFIXTURE_H
#define RENDERER_SHADERTESTFIXTURE_H

#ifndef GLFW_HEADLESS
static bool IS_HEADLESS = true;
#else
static bool IS_HEADLESS = GLFW_HEADLESS;
#endif

#endif //RENDERER_SHADERTESTFIXTURE_H

